skinparam shadowing false
skinparam monochrome true
skinparam sequenceParticipantBorderThickness 1
skinparam sequenceReferenceBorderThickness 1
skinparam sequenceGroupBorderThickness 1
skinparam TitleFontSize 20
skinparam sequenceTitleFontSize 20
skinparam sequenceTitleFontStyle plain