'''''''''
' Class '
'''''''''

class "StructVar" as STRUCT_VAR {
    value: float
    isConstant: bool
    isInitialized: bool
    isUsed : bool
}

class "Automaton" as CLASS_AUTOMATE {
    - dicoVariables: map<string, StructVar*>
    - currentLineError: int
    - currentCharPosError: int
    - programChecked: bool
    - programCanExecute: bool

    + readFile(string filename): int
    + transition(Symbol * symbol, State * newState): void
    + reduction(int reductionSize, Symbol * unterminalSymbol): void
    + accept(): void
    + execute(): void
    + optimizeProgram(): void
    + checkProgram(): void
    + aggregateBinaryOperatorExpression(): void
    + aggregateParenthesisExpression(): void
    + programmeToString(): string

    - computeNewSymbol(Symbol * symbol): void
    - init(): void
    - checkProgramVariablesUsed(): void
    - computeErrorLexicalUnexpectedSymbol(ErrorLexicalUnexpectedSymbol& error): void
    - computeErrorLexicalMissingSymbol(ErrorLexicalMissingSymbol& error): void
}

abstract class "State" as CLASS_ETAT {
    - name: String
    + {abstract} transition(Automaton & automaton, Symbol * symbol)
}

class "Lexer" as CLASS_LEXER {
    + {static} Symbol *readNextSymbol(string &stringToRead, string & stringSymbolDetected, int linePosition, int charPosition): void
}


'' Exceptions ------------------------------------------------
package "Exceptions" {

}

'' Symbols ------------------------------------------------

abstract class "Symbol" as CLASS_SYMBOLE {
    # id: int
    # numLineDetection : int
    # numCharDetection : int
    + Symbol(int id)
    + operator int(): int
    + {abstract} toString(): string
    + {abstract} isPersistent(): bool
    + {abstract} execute(map<string, StructVar*>& dicoVariables): void
    + {abstract} check(map<string, StructVar*>& dicoVariables): void
    + {abstract} optimize(map<string, StructVar*>& dicoVariables): Symbol*
    + {abstract} setSymbolDetectionPosition(int numLine, int numChar): void
}

class "SymbolUnit" as CLASS_SYMBOLE_POINT_VIRGULE extends CLASS_SYMBOLE {
    + SymbolUnit(enum TypeSymbolUnit)
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
}

class "SymbolUnterminal" as CLASS_SYMBOLE_UNTERMINAL extends CLASS_SYMBOLE {
    + SymbolUnterminal(enum TypeSymbolUnterminal)
    + toString(): string
}


abstract class "SymbolDeclaration" as CLASS_SYMBOLE_DECLARATION extends CLASS_SYMBOLE {
    + SymbolDeclaration(enum symbolIdTable idSymbol)
}
class "SymbolDeclarationVar" as CLASS_SYMBOLE_DECLARATION_VAR extends CLASS_SYMBOLE_DECLARATION {
    - variables: list<SymbolVariable*>
    + SymbolDeclarationVar()
    + execute(map<string, StructVar*>& dicoVariables): void
    + {static} analyse(string & stringToAnalyse, string & stringSymbolDetected): Symbol *
    + addVariable(SymbolVariable *pVariable, map<string, StructVar*>& dicoVariables): void
}
class "SymbolDeclarationConst" as CLASS_SYMBOLE_DECLARATION_CONST extends CLASS_SYMBOLE_DECLARATION {
    - constants: map<SymbolVariable*, float>
    - temporaryPtVariable: SymbolVariable *
    + SymbolDeclarationConst()
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + addConstant(SymbolVariable *pVariable): void
    + addConstantValue(float constantValue, map<string, StructVar*>& dicoVariables): void
}
abstract class "SymbolInstruction" as CLASS_SYMBOLE_INSTRUCTION extends CLASS_SYMBOLE {
    + SymbolInstruction(enum symbolIdTable idSymbol)
    + {abstract} affectExpression(SymbolExpression * expression): void
}
class "SymbolInstructionWrite" as CLASS_SYMBOLE_INSTRUCTION_ECRITURE extends CLASS_SYMBOLE_INSTRUCTION {
    + SymbolInstructionWrite()
    + execute(map<string, StructVar*>& dicoVariables): void
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + affectExpression(SymbolExpression * expression): void
    + check(map<string, StructVar*>& dicoVariables): void
    + optimize(map<string, StructVar*>& dicoVariables): Symbol *
    + toString(): string
}
class "SymbolInstructionRead" as CLASS_SYMBOLE_INSTRUCTION_VAR_LECTURE extends CLASS_SYMBOLE_INSTRUCTION {
    + SymbolInstructionRead()
    + execute(map<string, StructVar*>& dicoVariables): void
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + affectExpression(SymbolExpression * expression): void
    + check(map<string, StructVar*>& dicoVariables): void
    + toString(): string
}
class "SymbolInstructionAffect" as CLASS_SYMBOLE_INSTRUCTION_VAR_AFFECTATION extends CLASS_SYMBOLE_INSTRUCTION {
    + SymbolInstructionAffect()
    + SymbolInstructionAffect(SymbolVariable * variable)
    + execute(map<string, StructVar*>& dicoVariables): void
    + affectExpression(SymbolExpression * expression): void
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + check(map<string, StructVar*>& dicoVariables): void
    + detachExpressions(): void
    + toString(): string
}

abstract class "SymbolExpression" as CLASS_SYMBOLE_EXPRESSION extends CLASS_SYMBOLE {
    + SymbolExpression(enum symbolIdTable idSymbol)
    + affectExpression(SymbolExpression * expression): void
    + {abstract} eval(std::map<std::string, StructVar*>& dicoVariables): float
    + {abstract} checkEval(map<string, StructVar*>& dicoVariables): list<Error*> *
    + {abstract} optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + detachExpressions(): void
}

class "SymbolNumber" as CLASS_SYMBOLE_NOMBRE extends CLASS_SYMBOLE_EXPRESSION {
    - value: float

    + SymbolNumber()
    + SymbolNumber(string stringValue)
    + SymbolNumber(float value)
    + eval(map<string, StructVar*>& dicoVariables): float
    + eval(): float
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + checkEval(map<string, StructVar*>& dicoVariables): list<Error*> *
}
class "SymbolVariable" as CLASS_SYMBOLE_VARIABLE extends CLASS_SYMBOLE_EXPRESSION {
    - name: string

    + SymbolVariable(string varName)
    + eval(map<string, StructVar*>& dicoVariables): float
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + check(map<string, StructVar*>& dicoVariables): void
    + check(map<string, StructVar*>& dicoVariables, bool checkConstantUpdate): void
    + checkEval(map<string, StructVar*>& dicoVariables): list<Error*> *
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString(): string
}

abstract class "SymbolExpressionBinary" as CLASS_SYMBOLE_EXPRESSION_BINAIRE extends CLASS_SYMBOLE_EXPRESSION {
    + SymbolExpressionBinary(enum symbolIdTable idSymbol)
    + setOperands(SymbolExpression * leftOperand, SymbolExpression * rightOperand): void
}

class "SymbolExpressionParenthesis" as CLASS_SYMBOLE_EXPRESSION_PARENTHESE extends CLASS_SYMBOLE_EXPRESSION {
    + SymbolExpressionParenthesis()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + checkEval(map<string, StructVar*>& dicoVariables): list<Error*> *
    + toString(): string
    + setExpression(SymbolExpression * expression): void
    + detachExpressions(): void
}

class "SymbolExpressionBinaryAdd" as CLASS_SYMBOLE_EXPRESSION_BINAIRE_ADD extends CLASS_SYMBOLE_EXPRESSION_BINAIRE {
    + SymbolExpressionBinaryAdd()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString(): string
}
class "SymbolExpressionBinarySubstract" as CLASS_SYMBOLE_EXPRESSION_BINAIRE_SOUSTRACTION extends CLASS_SYMBOLE_EXPRESSION_BINAIRE {
    + SymbolExpressionBinarySubstract()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString(): string
}
class "SymbolExpressionBinaryMultiplication" as CLASS_SYMBOLE_EXPRESSION_BINAIRE_MULT extends CLASS_SYMBOLE_EXPRESSION_BINAIRE {
    + SymbolExpressionBinaryMultiplication()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString(): string
}
class "SymbolExpressionBinaryDivision" as CLASS_SYMBOLE_EXPRESSION_BINAIRE_DIV extends CLASS_SYMBOLE_EXPRESSION_BINAIRE {
    + SymbolExpressionBinaryDivision()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString(): string
}

class "RegexSymbol" as CLASS_REGEX_SYMBOL {
    - regexes : map<Regex::Symbol, RE2 *>

    - {static} findRegex(Regex::Symbol regexToFind): RE2 *
    - RegexSymbol()

    + {static} matches( string &stringToMatch, Regex::Symbol regexToMatch): MatchingResult
}

