@startuml
!include ../variables.puml
!include ../skin.puml

'' CLASS_AUTOMATE

CLASS_AUTOMATE --> CLASS_SYMBOLE : pileSymboles *
CLASS_AUTOMATE --> CLASS_ETAT : pileEtats *
CLASS_AUTOMATE --> CLASS_INSTRUCTION : listeInstructions *

'' Symboles

CLASS_SYMBOLE_INSTRUCTION_VAR --> CLASS_SYMBOLE_VARIABLE
CLASS_SYMBOLE_INSTRUCTION_VAR_AFFECTATION --> CLASS_SYMBOLE_EXPRESSION
CLASS_SYMBOLE_INSTRUCTION_ECRITURE --> CLASS_SYMBOLE_EXPRESSION

CLASS_SYMBOLE_EXPRESSION_BINAIRE o-- "2" INTERFACE_SYMBOLE_EXPR

'' Instructions

CLASS_ECRITURE --> CLASS_EXPRESSION
CLASS_AFFECTATION --> CLASS_EXPRESSION

CLASS_OPERATEUR_BINAIRE o-- "2" CLASS_EXPRESSION

@enduml