@startuml
!include ../variables.puml
!include ../skin.puml

'' CLASS_AUTOMATE

CLASS_AUTOMATE --> CLASS_SYMBOLE : instructions *
CLASS_AUTOMATE --> CLASS_SYMBOLE : stackSymbols *
CLASS_AUTOMATE --> CLASS_ETAT : stackStates *

'' Symboles

CLASS_SYMBOLE_INSTRUCTION_VAR_AFFECTATION --> CLASS_SYMBOLE_VARIABLE
CLASS_SYMBOLE_INSTRUCTION_VAR_LECTURE --> CLASS_SYMBOLE_VARIABLE

CLASS_SYMBOLE_INSTRUCTION_VAR_AFFECTATION --> CLASS_SYMBOLE_EXPRESSION
CLASS_SYMBOLE_INSTRUCTION_ECRITURE --> CLASS_SYMBOLE_EXPRESSION

CLASS_SYMBOLE_EXPRESSION_BINAIRE o-- "2" CLASS_SYMBOLE_EXPRESSION

CLASS_SYMBOLE_DECLARATION_VAR --> "1" CLASS_SYMBOLE_VARIABLE
CLASS_SYMBOLE_DECLARATION_CONST --> "*" CLASS_SYMBOLE_VARIABLE

CLASS_SYMBOLE_EXPRESSION_PARENTHESE --> "1" CLASS_SYMBOLE_EXPRESSION

@enduml