@startuml
!include variables.puml
!include ../../skin.puml


CLASS_ERROR_MISSING_LEXICAL_SYMBOL --> "-missingSymbol\n                            1" CLASS_SYMBOLE
CLASS_ERROR_LEXICAL_UNEXPECTED_SYMBOL --> "-expectedSymbol\n                            1" CLASS_SYMBOLE
CLASS_ERROR_LEXICAL_UNEXPECTED_SYMBOL --> "-instructionRead\n                            1" CLASS_SYMBOLE_INSTRUCTION_VAR_LECTURE


@enduml
