'''''''''
' Class '
'''''''''

class "StructVar" as STRUCT_VAR {
    value: float
    isConstant: bool
    isInitialized: bool
    isUsed : bool
}

class "Automaton" as CLASS_AUTOMATE {
    - dicoVariables: map<string, StructVar*>

    + readFile(string filename): int
    + transition(Symbol * symbol, State * newState): void
    + reduction(int reductionSize, Symbol * unterminalSymbol): void
    + accept(): void
    + execute(): void

    - computeNewSymbol(Symbol * symbol): void
    - init(): void
}

abstract class "State" as CLASS_ETAT {
    - name: String
    + {abstract} transition(Automaton & automaton, Symbol * symbol)
}

class "Lexer" as CLASS_LEXER {
    + {static} Symbol *readNextSymbol(string &stringToRead, string & stringSymbolDetected, int linePosition, int charPosition): void
}

'' Symbols ------------------------------------------------

abstract class "Symbol" as CLASS_SYMBOLE {
    # id: int
    # numLineDetection : int
    # numCharDetection : int
    + Symbol(int id)
    + operator int() const: int
    + {abstract} toString() const: string
    + {abstract} isPersistent() const: bool
    + {abstract} execute(map<string, StructVar*>& dicoVariables): void
    + {abstract} check(map<string, StructVar*>& dicoVariables): void
    + {abstract} optimize(map<string, StructVar*>& dicoVariables): Symbol*
    + {abstract} setSymbolDetectionPosition(int numLine, int numChar): void
}

enum "TypeSymbolUnit" as ENUM_SYMBOLE_UNITAIRE {
    SYMBOL_UNIT_PLUS
    SYMBOL_UNIT_MINUS
    SYMBOL_UNIT_MULT
    SYMBOL_UNIT_DIV
    SYMBOL_UNIT_EQUAL
    SYMBOL_UNIT_AFFECT
    SYMBOL_UNIT_ENDING_PAR
    SYMBOL_UNIT_OPENING_PAR
    SYMBOL_UNIT_COMMA
    SYMBOL_UNIT_SEMICOLON
    SYMBOL_UNIT_DOLLAR
}

enum "TypeSymbolUnterminal" as ENUM_SYMBOL_UNTERMINAL {
    SYMBOL_UNTERMINAL_P
    SYMBOL_UNTERMINAL_D
    SYMBOL_UNTERMINAL_D_PRIM
    SYMBOL_UNTERMINAL_V
    SYMBOL_UNTERMINAL_C
    SYMBOL_UNTERMINAL_I
    SYMBOL_UNTERMINAL_I_PRIM
    SYMBOL_UNTERMINAL_E
}

class "SymbolUnit" as CLASS_SYMBOLE_POINT_VIRGULE extends CLASS_SYMBOLE {
    + SymbolUnit(enum TypeSymbolUnit)
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
}

class "SymbolUnterminal" as CLASS_SYMBOLE_UNTERMINAL extends CLASS_SYMBOLE {
    + SymbolUnterminal(enum TypeSymbolUnterminal)
    + toString() const: string
}


abstract class "SymbolDeclaration" as CLASS_SYMBOLE_DECLARATION extends CLASS_SYMBOLE {
    + SymbolDeclaration(enum symbolIdTable idSymbol)
}
class "SymbolDeclarationVar" as CLASS_SYMBOLE_DECLARATION_VAR extends CLASS_SYMBOLE_DECLARATION {
    - variables: list<SymbolVariable*>
    + SymbolDeclarationVar()
    + execute(map<string, StructVar*>& dicoVariables): void
    + {static} analyse(string & stringToAnalyse, string & stringSymbolDetected): Symbol *
    + addVariable(SymbolVariable *pVariable, map<string, StructVar*>& dicoVariables): void
}
class "SymbolDeclarationConst" as CLASS_SYMBOLE_DECLARATION_CONST extends CLASS_SYMBOLE_DECLARATION {
    - constants: map<SymbolVariable*, float>
    - temporaryPtVariable: SymbolVariable *
    + SymbolDeclarationConst()
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + addConstant(SymbolVariable *pVariable): void
    + addConstantValue(float constantValue, map<string, StructVar*>& dicoVariables): void
}
abstract class "SymbolInstruction" as CLASS_SYMBOLE_INSTRUCTION extends CLASS_SYMBOLE {
    + SymbolInstruction(enum symbolIdTable idSymbol)
    + {abstract} affectExpression(SymbolExpression * expression): void
}
class "SymbolInstructionWrite" as CLASS_SYMBOLE_INSTRUCTION_ECRITURE extends CLASS_SYMBOLE_INSTRUCTION {
    + SymbolInstructionWrite()
    + execute(map<string, StructVar*>& dicoVariables): void
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + affectExpression(SymbolExpression * expression): void
    + check(map<string, StructVar*>& dicoVariables): void
    + optimize(map<string, StructVar*>& dicoVariables): Symbol *
    + toString() const: string
}
class "SymbolInstructionRead" as CLASS_SYMBOLE_INSTRUCTION_VAR_LECTURE extends CLASS_SYMBOLE_INSTRUCTION {
    + SymbolInstructionRead()
    + execute(map<string, StructVar*>& dicoVariables): void
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + affectExpression(SymbolExpression * expression): void
    + check(map<string, StructVar*>& dicoVariables): void
    + toString() const: string
}
class "SymbolInstructionAffect" as CLASS_SYMBOLE_INSTRUCTION_VAR_AFFECTATION extends CLASS_SYMBOLE_INSTRUCTION {
    + SymbolInstructionAffect()
    + SymbolInstructionAffect(SymbolVariable * variable)
    + execute(map<string, StructVar*>& dicoVariables): void
    + affectExpression(SymbolExpression * expression): void
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + check(map<string, StructVar*>& dicoVariables): void
    + detachExpressions(): void
    + toString() const: string
}

abstract class "SymbolExpression" as CLASS_SYMBOLE_EXPRESSION extends CLASS_SYMBOLE {
    + SymbolExpression(enum symbolIdTable idSymbol)
    + affectExpression(SymbolExpression * expression): void
    + {abstract} eval(std::map<std::string, StructVar*>& dicoVariables): float
    + {abstract} checkEval(map<string, StructVar*>& dicoVariables): list<Error*> *
    + {abstract} optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + detachExpressions(): void
}

class "SymbolNumber" as CLASS_SYMBOLE_NOMBRE extends CLASS_SYMBOLE_EXPRESSION {
    - value: float

    + SymbolNumber()
    + SymbolNumber(string stringValue)
    + SymbolNumber(float value)
    + eval(map<string, StructVar*>& dicoVariables): float
    + eval() const: float
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + checkEval(map<string, StructVar*>& dicoVariables): list<Error*> *
}
class "SymbolVariable" as CLASS_SYMBOLE_VARIABLE extends CLASS_SYMBOLE_EXPRESSION {
    - name: string

    + SymbolVariable(string varName)
    + eval(map<string, StructVar*>& dicoVariables): float
    + {static} analyse(std::string & stringToAnalyse, std::string & stringSymbolDetected): Symbol *
    + check(map<string, StructVar*>& dicoVariables): void
    + check(map<string, StructVar*>& dicoVariables, bool checkConstantUpdate): void
    + checkEval(map<string, StructVar*>& dicoVariables): list<Error*> *
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString() const: string
}

abstract class "SymbolExpressionBinary" as CLASS_SYMBOLE_EXPRESSION_BINAIRE extends CLASS_SYMBOLE_EXPRESSION {
    + SymbolExpressionBinary(enum symbolIdTable idSymbol)
    + setOperands(SymbolExpression * leftOperand, SymbolExpression * rightOperand): void
}

class "SymbolExpressionParenthesis" as CLASS_SYMBOLE_EXPRESSION_PARENTHESE extends CLASS_SYMBOLE_EXPRESSION {
    + SymbolExpressionParenthesis()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + checkEval(map<string, StructVar*>& dicoVariables): list<Error*> *
    + toString() const: string
    + setExpression(SymbolExpression * expression): void
    + detachExpressions(): void
}

class "SymbolExpressionBinaryAdd" as CLASS_SYMBOLE_EXPRESSION_BINAIRE_ADD extends CLASS_SYMBOLE_EXPRESSION_BINAIRE {
    + SymbolExpressionBinaryAdd()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString() const: string
}
class "SymbolExpressionBinarySubstract" as CLASS_SYMBOLE_EXPRESSION_BINAIRE_SOUSTRACTION extends CLASS_SYMBOLE_EXPRESSION_BINAIRE {
    + SymbolExpressionBinarySubstract()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString() const: string
}
class "SymbolExpressionBinaryMultiplication" as CLASS_SYMBOLE_EXPRESSION_BINAIRE_MULT extends CLASS_SYMBOLE_EXPRESSION_BINAIRE {
    + SymbolExpressionBinaryMultiplication()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString() const: string
}
class "SymbolExpressionBinaryDivision" as CLASS_SYMBOLE_EXPRESSION_BINAIRE_DIV extends CLASS_SYMBOLE_EXPRESSION_BINAIRE {
    + SymbolExpressionBinaryDivision()
    + eval(map<string, StructVar*>& dicoVariables) : float
    + optimizeExpression(map<string, StructVar*>& dicoVariables): SymbolExpression *
    + toString() const: string
}


'' Exceptions ------------------------------------------------
class "Error" as CLASS_ERROR {
    - number: int
    - level: int
    - numLineError: int
    - numCharError: int

    + Error(int number, int level, int numLineError, int numCharError)
    + what() const: const char*
    + toString() const: string
    + toString(int linePos, int charPos) const: string
}

class "ErrorArgument" as CLASS_ERROR_ARGUMENT {
    + ErrorArgument()
    + toString() const: string
}

class "ErrorLexical" AS CLASS_ERROR_LEXICAL extends CLASS_ERROR {
    + ErrorLexical(int number, int level, int numLineError, int numCharError)

}

class "ErrorSemantic" AS CLASS_ERROR_SEMANTIC extends CLASS_ERROR {
    + ErrorSemantic(int number, int level, int numLineError, int numCharError)

}

class "ErrorLexicalMissingSymbol" as CLASS_ERROR_MISSING_LEXICAL_SYMBOL extends CLASS_ERROR_LEXICAL {
    + ErrorLexicalMissingSymbol(int numLine, int numChar, Symbol * missingSymbol)
    + toString() const: string
    # toStringDetails() const: string
}

class "ErrorLexicalUnexpectedSymbol" as CLASS_ERROR_LEXICAL_UNEXPECTED_SYMBOL extends CLASS_ERROR_LEXICAL {
    # symbolName: string
    # isIgnored: bool

    + ErrorLexicalUnexpectedSymbol(const string & symbolName, int numLine, int numChar)
    + ErrorLexicalUnexpectedSymbol(const string & symbolName, int numLine, int numChar, Symbol* expectedSymbol)
    + ErrorLexicalUnexpectedSymbol(const string & symbolName, int numLine, int numChar, bool ignoreSymbol)
    + isSymbolIgnored() const: bool
    # toStringDetails() const: string
}

class "ErrorSemanticIncorrectNumericValue" as CLASS_ERROR_SEMANTIC_INCORRECT_NUMERIC_VALUE extends CLASS_ERROR_SEMANTIC {
    + ErrorSemanticIncorrectNumericValue(SymbolInstructionRead * instructionRead)
    # toStringDetails() const: string
}

class "ErrorSemanticVar" as CLASS_ERROR_SEMANTIC_VAR extends CLASS_ERROR_SEMANTIC {
    # varName : string

    + ErrorSemanticVar(int number, int level, const string & varName, int lineError, int charError)
    # toStringDetails() const: string
}

